using System.Threading.Channels;
using PogoInventory.Streaming;
namespace PogoInventory.Streaming.Scrcpy;
public sealed record StreamObservation(FrameId FrameId,TimeSpan? FrameInterval,double ChangeScore,double MotionScore,double Sharpness,bool IsStable,bool IsFrozen,bool ResolutionChanged,DateTimeOffset Utc);
public sealed class ObservationOptions {public int StableFrameCount{get;init;}=3;public double StableMotionThreshold{get;init;}=.02;public TimeSpan FreezeThreshold{get;init;}=TimeSpan.FromSeconds(1);}
public sealed class StreamingObservationService {
 readonly IStreamingFrameSource _source;readonly ObservationOptions _o;public StreamingObservationService(IStreamingFrameSource source,ObservationOptions? options=null){_source=source;_o=options??new();}
 public async IAsyncEnumerable<StreamObservation> ObserveAsync([System.Runtime.CompilerServices.EnumeratorCancellation]CancellationToken ct=default){FrameMetadata? prev=null;int stable=0;await foreach(var n in _source.WatchAsync(new FrameSubscription{Capacity=4},ct)){var m=n.Metadata;TimeSpan? interval=prev is null?null:m.Timestamp.MonotonicSinceStart-prev.Timestamp.MonotonicSinceStart;var motion=m.Quality.Motion;stable=motion<=_o.StableMotionThreshold?stable+1:0;var frozen=interval>_o.FreezeThreshold;yield return new(m.Id,interval,m.Stability.DifferenceScore,motion,m.Quality.Sharpness,stable>=_o.StableFrameCount,frozen,prev is not null&&prev.Descriptor!=m.Descriptor,m.Timestamp.CapturedAtUtc);prev=m;}}
}
public readonly record struct NormalizedRegion(double X,double Y,double Width,double Height){public void Validate(){if(X<0||Y<0||Width<=0||Height<=0||X+Width>1||Y+Height>1)throw new ArgumentOutOfRangeException(nameof(NormalizedRegion));}}
public sealed class FrameCropView : IDisposable {readonly IFrameLease _lease;public FrameCropView(IFrameLease lease,NormalizedRegion region){region.Validate();_lease=lease;var d=lease.Metadata.Descriptor;X=(int)Math.Floor(region.X*d.Width);Y=(int)Math.Floor(region.Y*d.Height);Width=Math.Max(1,(int)Math.Floor(region.Width*d.Width));Height=Math.Max(1,(int)Math.Floor(region.Height*d.Height));Stride=d.Stride;BytesPerPixel=d.PixelFormat==FramePixelFormat.Bgra32?4:throw new NotSupportedException("Zero-copy ROI currently requires BGRA32.");Offset=checked(Y*Stride+X*BytesPerPixel);}public int X{get;}public int Y{get;}public int Width{get;}public int Height{get;}public int Stride{get;}public int BytesPerPixel{get;}public int Offset{get;}public ReadOnlySpan<byte> GetRow(int row){if((uint)row>=(uint)Height)throw new ArgumentOutOfRangeException(nameof(row));return _lease.Pixels.Span.Slice(Offset+row*Stride,Width*BytesPerPixel);}public void Dispose()=>_lease.Dispose();}
public enum FrameCandidateKind{LatestFrame,LatestStableFrame,SharpestRecentFrame,MostChangedFrame,StableFramesAfterChange}
public enum FrameSelectionFailure{None,NoFrames,StabilityNotEstablished,Timeout}
public sealed record FrameCandidateResult(bool Success,IFrameLease? Lease,FrameSelectionFailure Failure,string Reason);
public interface IFrameCandidateSelector{ValueTask<FrameCandidateResult>SelectAsync(FrameCandidateKind kind,TimeSpan timeout,CancellationToken ct=default);}
public sealed class FrameCandidateSelector(IStreamingFrameSource source):IFrameCandidateSelector {public async ValueTask<FrameCandidateResult>SelectAsync(FrameCandidateKind kind,TimeSpan timeout,CancellationToken ct=default){using var linked=CancellationTokenSource.CreateLinkedTokenSource(ct);linked.CancelAfter(timeout);try{var q=kind switch{FrameCandidateKind.LatestFrame=>new FrameQuery{MinimumCompositeQuality=0},FrameCandidateKind.LatestStableFrame or FrameCandidateKind.StableFramesAfterChange=>new FrameQuery{RequireStable=true,MinimumStableFrames=3,MinimumStableDuration=TimeSpan.FromMilliseconds(100),MinimumCompositeQuality=0},FrameCandidateKind.SharpestRecentFrame=>new FrameQuery{MinimumCompositeQuality=.1},FrameCandidateKind.MostChangedFrame=>new FrameQuery{MinimumCompositeQuality=0},_=>new FrameQuery()};while(true){var lease=await source.GetLatestAsync(q,linked.Token);if(lease!=null)return new(true,lease,FrameSelectionFailure.None,"Selected.");await Task.Delay(20,linked.Token);}}catch(OperationCanceledException)when(!ct.IsCancellationRequested){return new(false,null,kind is FrameCandidateKind.LatestStableFrame or FrameCandidateKind.StableFramesAfterChange?FrameSelectionFailure.StabilityNotEstablished:FrameSelectionFailure.Timeout,"No frame satisfied the bounded selection request.");}}}
