<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../PogoInventory.Streaming/PogoInventory.Streaming.csproj" />
    <ProjectReference Include="../PogoInventory.Streaming.Scrcpy/PogoInventory.Streaming.Scrcpy.csproj" />
  </ItemGroup>
</Project>
